// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Hand = (function(_super) {
    __extends(Hand, _super);

    function Hand() {
      _ref = Hand.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Hand.prototype.model = Card;

    Hand.prototype.initialize = function(array, deck, isDealer) {
      this.deck = deck;
      this.isDealer = isDealer;
    };

    Hand.prototype.hit = function() {
      var scores;
      if (!this.isDealer) {
        this.add(this.deck.pop()).last();
      }
      scores = this.scores();
      if (this.isDealer) {
        console.log(this.at(0));
        this.at(0).flip();
        scores = this.scores();
        while (scores[0] < 17) {
          this.add(this.deck.pop()).last();
          scores = this.scores();
        }
        return this.trigger('ended');
      }
    };

    Hand.prototype.stand = function() {};

    Hand.prototype.scores = function() {
      var hasAce, score;
      hasAce = this.reduce(function(memo, card) {
        return memo || card.get('value') === 1;
      }, false);
      score = this.reduce(function(score, card) {
        return score + (card.get('revealed') ? card.get('value') : 0);
      }, 0);
      if (hasAce) {
        return [score, score + 10];
      } else {
        return [score];
      }
    };

    Hand.prototype.bestScore = function() {
      var best, score, scores, _i, _len;
      scores = this.scores();
      best = 0;
      for (_i = 0, _len = scores.length; _i < _len; _i++) {
        score = scores[_i];
        if ((best < score && score <= 21)) {
          best = score;
        }
      }
      if (best === 0) {
        best = "BUST";
        debugger;
        this.trigger('ended');
      }
      return best;
    };

    return Hand;

  })(Backbone.Collection);

}).call(this);
